#!/bin/bash
# update_cover_params.sh - Update cover parameters dynamically

PROJECT_META="${1:-2}"
PROJECT_ETAPA="${2:-2}"
PROJECT_TITLE="${3:-Relatório Trimestral de Acompanhamento}"
PROJECT_MONTH="${4:-Agosto}"
PROJECT_YEAR="${5:-2025}"
PRODUCT_NUMBER="${6:-1}"

# Output file for cover parameters
PARAMS_FILE="settings/cover_params.tex"

# Generate the cover parameters file
cat > "$PARAMS_FILE" << EOF
% settings/cover_params.tex
% Dynamically generated cover parameters
% DO NOT EDIT - This file is auto-generated by make

% Cover configuration
\renewcommand{\projectMeta}{$PROJECT_META}
\renewcommand{\projectEtapa}{$PROJECT_ETAPA}
\renewcommand{\projectTitle}{$PROJECT_TITLE}
\renewcommand{\projectMonth}{$PROJECT_MONTH}
\renewcommand{\projectYear}{$PROJECT_YEAR}
\renewcommand{\productNumber}{$PRODUCT_NUMBER}
EOF

echo "✅ Cover parameters updated:"
echo "   Meta $PROJECT_META Etapa $PROJECT_ETAPA"
echo "   Title: $PROJECT_TITLE"
echo "   Date: $PROJECT_MONTH $PROJECT_YEAR"
echo "   Product: $PRODUCT_NUMBER"